//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MundoMusical
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracion
    {
        public int idconfig { get; set; }
        public string ticketprintname { get; set; }
        public string etiquetaprintname { get; set; }
        public string globalprintname { get; set; }
        public Nullable<int> defaultcliente { get; set; }
    
        public virtual cliente cliente { get; set; }
    }
}
