//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MundoMusical
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbmodel : DbContext
    {
        public dbmodel()
            : base("name=dbmodel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<configuracion> configuracion { get; set; }
        public virtual DbSet<detalle> detalles { get; set; }
        public virtual DbSet<factura> facturas { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<modo_pago> modo_pago { get; set; }
        public virtual DbSet<producto> productos { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
        public virtual DbSet<tienda> tiendas { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<venta> ventas { get; set; }
    }
}
