//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MundoMusical
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int idlogin { get; set; }
        public int idusuario { get; set; }
        public System.TimeSpan hora_inicio { get; set; }
        public Nullable<System.TimeSpan> hora_cierre { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
